### ISSUE TITLE
Add the option to specify a token

### ISSUE THREAD

**Issue by strongishllama** [ahmadnassri/action-google-cloud-sql-proxy#45]
Now that GitHub supports [OIDC authentication](https://github.com/google-github-actions/auth#usage) with GCP, it would be great if we could specify the OIDC token as a flag instead of the credentials file.

I'm happy to work on a PR for this, I'd be in favour of doing a major version bump and removing the credentials file support altogether seeing as the service account authentication with the GCP Auth action is deprecated.

The new workflow would look something like this.
```yaml
- name: Authenticate to Google Cloud
  id: auth
  uses: google-github-actions/auth@v0.8.0
  with:
    token_format: access_token
    workload_identity_provider: WORKLOAD_IDENTITY_PROVIDER
    service_account: SERVICE_ACCOUNT
- name: Start CloudSQL Proxy
  uses: ahmadnassri/action-google-cloud-sql-proxy@v2
  with:
    token: ${{ steps.auth.outputs.access_token }}
    connection: ${{ inputs.database-instance-name }}
    port: 5432
```

You can find the quick and dirty changes I made to my [fork](https://github.com/strongishllama/action-google-cloud-sql-proxy) to test it and it appears to be working fine.

Cheers!
